<a href="https://colab.research.google.com/github/olivetahonsu/Pytorch_tutorials/blob/main/Intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor:** A torch.Tensor is a multi-dimensional array of the same containing elements of the same data type.

- It similar to Numpy array but with more power.
- Can work both on CPU
and GPU.
- The defualt data type is float32.
- More suitable for deep learning than Numpy

In [2]:
# Import torch
import torch

In [3]:
# Create tensor
x = torch.tensor([1.0, 2.0, 3.0])

In [4]:
print(x) # output tensor

print(x.shape) # shape of tensor

print(x.dtype) # data type of tensor

print(type(x)) # type of tensor

tensor([1., 2., 3.])
torch.Size([3])
torch.float32
<class 'torch.Tensor'>


In [7]:
# Create a 1D tensor with random values
y = torch.rand(3)

print(y)

tensor([0.0288, 0.0486, 0.0248])


- **Math Operations on tensors**

In [8]:
a = torch.tensor([[1.0, 2.0, 3.0], [1.0, 3.0, 4.0]])
b = torch.tensor([4.0, 5.0, 6.0])

# Sum of tensors
print(a + b)

# Multiplication of tensors
print(a * b)

# Subtraction of tensors
print(a - b)

# Division of tensors
print(a/b)

# Mean of tensor
print(a.mean())

tensor([[ 5.,  7.,  9.],
        [ 5.,  8., 10.]])
tensor([[ 4., 10., 18.],
        [ 4., 15., 24.]])
tensor([[-3., -3., -3.],
        [-3., -2., -2.]])
tensor([[0.2500, 0.4000, 0.5000],
        [0.2500, 0.6000, 0.6667]])
tensor(2.3333)


In [9]:
# Tensor with power
x = torch.tensor([10.0, 20.0, 30.0])
y = x ** 2
print(y)
print(y.shape)


tensor([100., 400., 900.])
torch.Size([3])


- **Automatic Differentiation (Autograd) in tensors**

In [12]:

x = torch.tensor(2.0, requires_grad=True)
y = x ** 2

y.backward()

print(x.grad)

tensor(4.)


- **Reshape and View**

In [8]:
my_tensor = torch.tensor(range(30))

my_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
# Reshape tensor
reshaped_tensor = my_tensor.reshape(1, 30)

reshaped_tensor

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [15]:
# Change a tensor value
reshaped_tensor[0, 0] = 100

reshaped_tensor

tensor([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29]])

In [18]:
# Grab an item in tensor
my_tensor[0]

tensor(100)